"""add experience_months column to candidates

Revision ID: 1cd6979af7ec
Revises: 7cc541d28e19
Create Date: 2025-09-12 23:13:01.903553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cd6979af7ec'
down_revision = '7cc541d28e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience_months', sa.Integer(), nullable=True))

    with op.batch_alter_table('cv_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_name', sa.String(length=100), nullable=False))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'conversations', ['conversation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('cv_history', schema=None) as batch_op:
        batch_op.drop_column('cv_name')

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('experience_months')

    # ### end Alembic commands ###
