"""Add cv_id to applications

Revision ID: 6e9ef96cb7e4
Revises: 8388d34ea02f
Create Date: 2025-09-13 10:52:52.246662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e9ef96cb7e4'
down_revision = '8388d34ea02f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'cv_history', ['cv_id'], ['id'])
        batch_op.drop_column('cv_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_file', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cv_id')

    # ### end Alembic commands ###
