"""Add isPremiumActive to User and create Payment table

Revision ID: 76a37fa8cce9
Revises: 
Create Date: 2025-09-10 13:54:29.438371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a37fa8cce9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isPremiumActive', sa.Boolean(), nullable=False))

    # Create payments table
    op.create_table('payments',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('gateway', sa.String(length=100), nullable=False),
        sa.Column('transaction_date', sa.DateTime(), nullable=False),
        sa.Column('account_number', sa.String(length=100), nullable=True),
        sa.Column('sub_account', sa.String(length=250), nullable=True),
        sa.Column('amount_in', sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column('amount_out', sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column('accumulated', sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column('code', sa.String(length=250), nullable=True),
        sa.Column('transaction_content', sa.Text(), nullable=True),
        sa.Column('reference_number', sa.String(length=255), nullable=True),
        sa.Column('body', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('isPremiumActive')

    # ### end Alembic commands ###
