"""Add public_url to cv_history

Revision ID: 8388d34ea02f
Revises: 7cc541d28e19
Create Date: 2025-09-13 10:12:47.966247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8388d34ea02f'
down_revision = '7cc541d28e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('conversation_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('conversation_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('cv_history', schema=None) as batch_op:
        batch_op.drop_column('public_url')

    # ### end Alembic commands ###
